version: '3.8'

services:
  postgres:
    image: postgres:15  # Используемый образ PostgreSQL
    container_name: my_postgres_old    # Имя контейнера
    environment:
      POSTGRES_USER: postgres  # Имя пользователя для базы данных
      POSTGRES_PASSWORD: password  # Пароль для пользователя
      POSTGRES_DB: goit2034-dev  # Имя базы данных по умолчанию
    ports:
      - "5438:5432"  # Пробрасываем порт 5432 на 5438
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Монтируем volume для сохранения данных
    networks:
      - postgres-network  # Подключаем к сети

  pgadmin:
    image: dpage/pgadmin4:8.2  # Используемый образ pgAdmin
    container_name: my_pgadmin_old  # Имя контейнера для pgAdmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com  # Email для входа в pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin  # Пароль для pgAdmin
    ports:
      - "5050:80"  # Пробрасываем порт 80 на 5050 для доступа к веб-интерфейсу
    depends_on:
      - postgres  # Зависимость от PostgreSQL
    volumes:
      - pgadmin_data:/var/lib/pgadmin  # Volume для данных pgAdmin
    networks:
      - postgres-network  # Подключаем к сети

networks:
  postgres-network:
    driver: bridge

volumes:
  postgres_data:  # Volume для данных PostgreSQL
  pgadmin_data:  # Volume для данных pgAdmin

# docker network ls   -  see all networks
# docker network inspect coremodule3_postgres-network    - see network details